Added message for low funds
f-klubben/stregsystemet pull request #181
Opened 2019-10-01 12:50 UTC by joandrsn

If you have under a balance under 5000, you should get a message, notifying you that you might soon be banned.

2019-10-03 15:56 UTC, VirtualSatai commented on stregsystem/templates/stregsystem/index_sale.html
> +    Tilbagestående beløb: {{newmemberbalance}}
Consider adding a hint that they should insert more money soon.

2019-10-07 08:49 UTC, jenrik commented
I don't think we should leave peoples balance visible, I think either there should be timeout after which the message disappear, or the message should only state that the account balance is below 5000, or both

2019-10-10 19:29 UTC, joandrsn commented
Agree. I would like to wait for #182 to be merged.

2020-04-08 07:51 UTC, jenrik commented
@joandrsn #182 has been merged, should we look at getting this merged too?

2020-10-02 10:06 UTC, joandrsn commented
I have updated the code to remove the remaning amount, using the same method as in #182 
Maybe @hrjakobsen or @cogitantium can review this PR?

2020-10-02 14:15 UTC, cogitantium requested changes

2020-10-02 14:15 UTC, cogitantium commented on stregsystem/templates/stregsystem/index_sale.html
> +    Tilbagestående beløb: <span class="remainingbalance">{{newmemberbalance}}</span>
```suggestion
    Balance: <span class="remainingbalance">{{newmemberbalance}}</span>
```

This is just my preference

2020-10-03 13:46 UTC, cogitantium approved these changes
LGTM :ok_hand:

2020-10-05 11:04 UTC, jenrik approved these changes

2023-08-18 08:17 UTC, JakobTopholt commented
LGTM

2023-09-03 10:20 UTC, falkecarlsen commented
@joandrsn made feature catch up and added blinking, note that only Chrome-based browsers load `gdpr.js` for some reason.

2023-09-03 10:20 UTC, merged