Set timezone to Europe/Copenhagen
f-klubben/stregsystemet pull request #212
Opened 2020-10-03 20:44 UTC by cogitantium

Fixes #211.

Making a separate PR instead of simply updating #209 is _naturally_ not a case of pumping my PR-count during hacktober.

2020-10-07 10:46 UTC, VirtualSatai requested changes

2020-10-07 10:46 UTC, VirtualSatai commented on treo/settings.py
> +TIME_ZONE = 'Europe/Copenhagen'
Du bliver nødt til at tjekke at dette ikke giver historiske konsekvenser som er utilsigtede, det er grunden til dette ikke er sket før nu. Hvis alle historiske salgbliver forskudt 1/2 timer, så er dette ikke helt acceptabelt. Kunne man lave dette som en unit-test, ellers bare tjek manuelt.

2020-10-07 12:14 UTC, hrjakobsen commented on treo/settings.py
> +TIME_ZONE = 'Europe/Copenhagen'
Er historisk data ikke også gemt i UTC? 
TIME_ZONE bliver, så vidt jeg ved, kun brugt til at vise data anderledes. Det hele bliver stadig gemt i UTC i databasen.

2020-10-07 14:52 UTC, VirtualSatai commented on treo/settings.py
> +TIME_ZONE = 'Europe/Copenhagen'
Hvis det er rigtigt, så er der ingen problem :D 
Tror den relevante dokumentation er her: ttps://docs.djangoproject.com/en/3.1/ref/settings/#std:setting-TIME_ZONE

2020-10-07 14:52 UTC, VirtualSatai approved these changes

2020-10-07 15:10 UTC, joandrsn approved these changes

2020-10-07 15:12 UTC, cogitantium commented on treo/settings.py
> +TIME_ZONE = 'Europe/Copenhagen'
Det er i alt fald min opfattelse, jeg prøvede at simulere noget historisk data på tværs af timezones o.lign. og det virkede ikke til at skabe problemer.

*det er forresten Django 2.2 LTS vi bruger*

2020-10-07 15:15 UTC, cogitantium commented on treo/settings.py
> +TIME_ZONE = 'Europe/Copenhagen'
> Er historisk data ikke også gemt i UTC?

Jo, siden første commit har `USE_TZ` været sat sand og `TIME_ZONE` sat til UTC i settings.

2020-11-04 08:21 UTC, cogitantium commented
Closes #209

2020-11-12 17:00 UTC, cogitantium commented on treo/settings.py
> +TIME_ZONE = 'Europe/Copenhagen'
Jeg har lige tested featuren imod produktions-data, og med stikprøver fra både vinter og sommertid kan jeg se at den overholder UTC i database og kun formaterer til GMT+1/2 på frontend.

2020-11-18 17:16 UTC, merged