Bugfix escape username
f-klubben/stregsystemet pull request #214
Opened 2020-10-08 15:04 UTC by joandrsn

The `sales_hint` was unescaped, resulting in the following hint:
![image](https://user-images.githubusercontent.com/5766695/95477076-3e476280-0988-11eb-9661-5bbcc6d0804a.png)

After this fix, it should be presented as this:
![image](https://user-images.githubusercontent.com/5766695/95477141-4f906f00-0988-11eb-9247-edf0e94c3c9c.png)

If this is accepted, please squash the commit since I made some indentation errors :)

2020-10-09 07:49 UTC, hrjakobsen requested changes

2020-10-09 07:49 UTC, hrjakobsen commented on stregsystem/templates/stregsystem/menu.html
> +{% endblock %}
I think it's better to keep the `products` block as it is, and start a new {% autoescape off %} above the saleshints, as the `sale_hint` is not part of the product list. and will make extending this file (if ever required) more difficult.

2020-10-09 15:57 UTC, joandrsn commented on stregsystem/templates/stregsystem/menu.html
> +{% endblock %}
Thank you! I changed it.

2020-10-10 12:50 UTC, hrjakobsen approved these changes

2020-10-10 13:37 UTC, cogitantium approved these changes

2020-11-18 17:18 UTC, merged