Adds support for videos to be displayed in the kiosk
f-klubben/stregsystemet pull request #216
Opened 2020-10-10 08:34 UTC by GeneralDenmark

Fixes #147

This PR changes the table kioskitem to have a django file input field instead of an image field, as image field is inheriting from input field, and we are not using the specific parameters for image fields, the conversion between these fields are seamless.

For the frontend to support a video, we just needed to inject the video element into the dummy div.
 
As the ImageField had its own validation regarding what file extensions that it could take (only valid image files), I had to create a custom validator for the filed, to avoid people uploading none-image and none-movie files.

2020-10-10 14:47 UTC, cogitantium requested changes
Nice, great to finally have this feature! A few things:

1. The model field should reflect that is is media and not just images in admin like this. I'm not sure how to handle this migration nicely as it requires setting defaults for existing kiosk items:
![image](https://user-images.githubusercontent.com/11318702/95657690-1ab22280-0b16-11eb-92c8-58017a7cf7c0.png)

1. When viewing media in a more vertical format than 16:9, the F-Klubben splash image is visible in the background. It seems like any media is simply displayed above the splash image:
![image](https://user-images.githubusercontent.com/11318702/95658007-05d68e80-0b18-11eb-91ae-345e88b13351.png)

2020-10-11 18:45 UTC, GeneralDenmark commented
When you are writing the reviews, please use the "request change" feature to make change requests, you've done that for two change requests (even though they were comments on wrong part of the code). It makes it easier for the one having to make the changes, to see the progress.

And when completing the requested changes, its possible to mark them as resolved :) 

else, good review, the changes you've requested have been completed.

2020-10-13 20:25 UTC, cogitantium reviewed
Looks good, I still have some thoughts on the migrations and I'm not certain on which approach would be best. 

I think @hrjakobsen, @VirtualSatai, and/or @DelusionalLogic may be able to give some input.

2020-10-13 20:25 UTC, cogitantium commented on stregsystem/migrations/0011_auto_20201011_1819.py
> +    ]
Do we want to include this auto-migration with this PR?

2020-10-13 20:25 UTC, cogitantium commented on kiosk/models.py
> +    media = models.FileField(upload_to='kiosk', null=False, validators=[validate_file_extension])
Is it possible to update (with similar tooling as you've written in kiosk/migrations/0006_auto_20201010_1459.py ) the historical `image` kiosk-entries to become `media` kiosk-entries, such that we only have one filefield; `media`?

I think someone more competent at Django than me should have a look at this.

2020-10-14 12:26 UTC, hrjakobsen commented on stregsystem/migrations/0011_auto_20201011_1819.py
> +    ]
No, it should be a PR in itself (or directly committed to next i guess)

2020-10-18 18:57 UTC, GeneralDenmark commented on kiosk/models.py
> +    media = models.FileField(upload_to='kiosk', null=False, validators=[validate_file_extension])
It can be removed, I wrote a migration script for moving all the data from image to media. The fact that it is still in the PR, is a mistake on my part. I'll remove that posthaste.

2020-10-18 18:59 UTC, GeneralDenmark commented on stregsystem/migrations/0011_auto_20201011_1819.py
> +    ]
Yes, this can be removed, I caught it in the first commit, but must've missed it in my second.

2020-10-19 07:00 UTC, GeneralDenmark commented
As the two previous change requests was blatant mistakes on my part, I removed them from history. Trump would be proud.

2020-10-29 14:51 UTC, cogitantium approved these changes
LGTM

2020-11-11 20:09 UTC, DelusionalLogic approved these changes
Showing the splash screen seems janky. I love it!

Edit: It's actually not always the splash screen. The way we flip the kiosk images without flickering is by having 2 elements. One in front and one in back. The one in the back has the next image so it has time to load.

To put it simply, you will have the next image behind the video if it doesn't fill the entire screen. I think this was also a problem with images though, so who cares.

2020-11-13 07:55 UTC, GeneralDenmark commented
> Showing the splash screen seems janky. I love it!
> 
> Edit: It's actually not always the splash screen. The way we flip the kiosk images without flickering is by having 2 elements. One in front and one in back. The one in the back has the next image so it has time to load.
> 
> To put it simply, you will have the next image behind the video if it doesn't fill the entire screen. I think this was also a problem with images though, so who cares.

@DelusionalLogic, I think this PR also fixes that problem, as I make sure to clear the background image and my bowel system before changing background image.


@cogitantium Thanks for the changes, although I don't really agree on the necessity for renaming all of the migrations, its not a problem, and if you wanna do it, :gunhands: you are more than whale-cum!

2020-11-18 17:17 UTC, merged