Add ranking feature to userinfo
f-klubben/stregsystemet pull request #256
Opened 2021-09-27 16:23 UTC by falkecarlsen

Users can click 'Rangliste' under userinfo to get their ranking in all categories:
![image](https://user-images.githubusercontent.com/11318702/134947430-4a774128-fdb0-43d2-9fd8-a9ddb6ec77ab.png)

Unfortunately this is slow as molasses, which could be alleviated by caching - but that's effort.
Currently this is all time, should probably also have a 'since Fjulefrokost' or possibly allow users to specify a timerange.

2021-11-12 12:36 UTC, Zaph-x requested changes
![image](https://user-images.githubusercontent.com/35431127/141468073-24251eac-81d0-45b9-89da-99b2349e7d7b.png)
It is possible to apply a greater from date, than to date

2021-11-26 12:12 UTC, falkecarlsen commented on stregsystem/views.py
> +            for x in list(map(lambda x: {x: get_product_ids_for_category(x)}, list(Category.objects.all())))
Yeah, you're right - thanks!

2021-11-26 12:12 UTC, falkecarlsen commented
> It is possible to apply a greater from date, than to date

Fixed in a2bb5e6

2021-11-26 12:29 UTC, Zaph-x approved these changes

2021-12-13 16:00 UTC, merged