Add nix-shell setup for easy development
f-klubben/stregsystemet pull request #272
Opened 2021-10-04 17:08 UTC by SEbbaDK

The shell specification uses the current requirements.txt and should add no maintenance.
It makes it very simple for nix users on linux/mac to get ready to work on stregsystemet via `nix-shell`.
We can hopefully remove the two custom packages later when @jbjjbjjbj upstreams the packages to `nixpkgs`

2021-10-04 17:21 UTC, jbjjbjjbj commented on shell.nix
> +    src = ./.;
Why add a `src` as this is only a shell.

```suggestion
```

2021-10-04 17:29 UTC, SEbbaDK commented on shell.nix
> +, pythonPackages ? pkgs.python39Packages
```suggestion
, python ? pkgs.python36
, pythonPackages ? pkgs.python36Packages
```
Since the README says we should use python 3.6, we should do the same in the shell

2021-10-04 17:41 UTC, falkecarlsen requested changes
I've heard it doesn't matter if the 'main' nix-file specifies py-version, but just for good order

2021-10-04 17:41 UTC, falkecarlsen commented on django-debug-toolbar.nix
> +, pythonPackages ? pkgs.python39Packages
```suggestion
, pythonPackages ? pkgs.python36Packages
```

2021-10-04 17:41 UTC, falkecarlsen commented on django-select2.nix
> +, pythonPackages ? pkgs.python39Packages
```suggestion
, pythonPackages ? pkgs.python36Packages
```

2024-05-14 23:30 UTC, Mast3rwaf1z commented
@krestenlaust it works with nixos-23.05, but later versions like 23.11 or unstable seems to have checks in place against the older version of django we use.

There seems to be a missing dependency to a module called `django.utils.six`, i don't know what this is.

Also this fork is very outdated

I would suggest that if we want a nix shell, i would prefer it to be written as a flake instead, and rewritten to work with the current system.

2024-05-15 05:30 UTC, krestenlaust commented
Thanks you for the insight @Mast3rwaf1z 👌

2024-05-15 14:38 UTC, soupglasses commented
Waiting for #409 so we dont need to package ancient versions of Python dependencies. :sunglasses:

2024-12-03 00:48 UTC, Mast3rwaf1z commented
@krestenlaust with #459 merged, I think we should close this pr, it basically does the same with less flexibility

2024-12-03 11:38 UTC, krestenlaust commented
Fixed by #459

2024-12-03 11:38 UTC, closed without merging