Caffeine
f-klubben/stregsystemet pull request #290
Opened 2021-11-29 13:21 UTC by Idadorable

A caffeine calculator that displays mg of caffeine in your body when you buy caffeine products.
It also calculates the number of coffee cups corresponding to your caffeine level.
The calculator is only displayed when you buy a caffeine product
Lastly, it also finds the coffee master of the week!

caffeine calculator:
![image](https://user-images.githubusercontent.com/44022898/143875243-a79efbda-b9c9-4ced-907a-bbbefe4d6b49.png)
![image](https://user-images.githubusercontent.com/44022898/143875374-539a56d6-0dec-426f-9d36-7e07d5537169.png)

Coffe master:
![image](https://user-images.githubusercontent.com/44022898/143875112-cdd26485-8128-43bf-8ab6-1455ceb4ba99.png)

2021-11-29 19:01 UTC, falkecarlsen requested changes
Nice, more ranking is more better :+1:

2021-11-30 13:52 UTC, Idadorable commented on stregsystem/migrations/0015_product_caffine_content_ml.py
> +    ]
We have create a single file now :)

2021-11-30 13:55 UTC, Idadorable commented on stregsystem/tests.py
> +        # category
We now use pk=6  ✌️

2021-11-30 14:35 UTC, AndersSpringborg requested changes

2021-11-30 14:35 UTC, AndersSpringborg commented on stregsystem/views.py
> +from django import forms, template
```suggestion
from django import forms
```

2021-11-30 14:35 UTC, AndersSpringborg commented on stregsystem/views.py
> +from django.template.defaultfilters import stringfilter
```suggestion
```

2021-11-30 14:44 UTC, AndersSpringborg approved these changes
Tror den er der nu! 🤠

2021-12-13 15:08 UTC, falkecarlsen approved these changes
I disliked the addition of the two dependencies, so I refactored the feature and added some more tests :shipit:

2021-12-13 15:11 UTC, Zaph-x approved these changes
☕

2021-12-13 15:20 UTC, merged