Add named IDs to stregsystemet
f-klubben/stregsystemet pull request #295
Opened 2022-02-11 17:14 UTC by Zaph-x

This pull request adds named IDs to stregsystemet.
This has been requested by several fembers since STS got named IDs as shorthands for buying.
The named IDs do not change the way products are parsed when purchases, as they are handled in pre-processing. This means the user does not need to know about the IDs, however may use them if they are known to the user.
An example of a named ID purchase is `tester øl` which would be preprocessed to `tester 14` by looking for a named ID in the database linked to øl. If an ID is not found, the string is left as is (e.g. `tester asdfghjkl` would remain the same) and give a parse error.

2022-02-22 13:53 UTC, hrjakobsen reviewed
I haven't tested this, only read the code changes, and left some comments based on that. I think some more validation of the names of `NamedProduct` are required.

2022-02-22 13:53 UTC, hrjakobsen commented on pyproject.toml
> +target-version = ['py37']
I feel like this should be a separate PR. Isn't related to named IDs

2022-02-22 13:53 UTC, hrjakobsen commented on stregsystem/models.py
> +        super(NamedProduct, self).save(*args, **kwargs)
Isn't this the default behaviour? Why do we need to override `save`?

2022-02-22 13:53 UTC, hrjakobsen commented on stregsystem/urls.py
> +    ),
Shouldn't be unfolded by `black`

2022-02-22 13:53 UTC, hrjakobsen commented on stregsystem/views.py
> +    return JsonResponse(items_dict, json_dumps_params={'ensure_ascii': False})
This looks like a debug page that we shouldn't include

2022-02-22 13:53 UTC, hrjakobsen commented on stregsystem/views.py
> +            _item = NamedProduct.objects.filter(name=item.split(':')[0].lower() if ':' in item else item)
Adding a `NamedProduct` with a name including ":" or " " would break this function, we should probably check for that somewhere.

2022-02-22 13:53 UTC, hrjakobsen commented on treo/settings.py
> +}
Not relevant to this PR

2022-02-22 13:53 UTC, hrjakobsen commented on treo/urls.py
>      ] + urlpatterns
Not relevant to this PR

2022-02-23 15:48 UTC, VirtualSatai requested changes

2022-02-24 15:10 UTC, hrjakobsen requested changes

2022-02-24 15:10 UTC, hrjakobsen commented on stregsystem/models.py
> +        super(NamedProduct, self).save(*args, **kwargs)
This should be implemented as a [validator](https://docs.djangoproject.com/en/3.2/ref/validators/) for the `name` field

2022-03-10 16:29 UTC, joandrsn approved these changes
:shipit:

2022-03-16 08:33 UTC, hrjakobsen approved these changes
I think alias handling in views could be handled better. 

* Why do we show a random alias instead of all? 
* Why do we *have* to show an alias if none exist? (N/A -> id)

However this is nothing that blocks merging.

2022-05-11 15:07 UTC, merged