Feature signup
f-klubben/stregsystemet pull request #297
Opened 2022-03-11 13:00 UTC by jonasKjellerup

The pull request addresse issue #254 

The pull request adds the following:

- A signup form (linked to via "Tilmeld" button on the index page)
- Adds a `Command` for automatically processing signup payments

The new signup flow would be as follows:

1. The user fills out the signup form.
2. On success the user will be redirected to a status page with a clickable (for mobile users) QR-code.
3. Once payment has been registered the account will be activated and a welcome mail will be sent.

2022-03-11 18:21 UTC, falkecarlsen commented on stregsystem/views.py
> +    form = SignupForm(request.POST) if is_post else SignupForm()
Redundant, can be reduced to one statement. If request.POST, then it is post.

2022-11-18 14:54 UTC, Nielswps requested changes
I think this would be a brilliant feature during events for members where non-members might attend, wanting to signup, good job :+1: 
Just some minor string typos

2022-11-18 14:54 UTC, Nielswps commented on stregsystem/forms.py
> +                                               'max_length': 'Længden af `Brugernavn må ikke overstige 16 tegn.`'})
Misplacement of '\`', should be 'Længden af `Brugernavn` må ikke overstige 16 tegn.'

2022-11-18 14:54 UTC, Nielswps commented on stregsystem/forms.py
> +                                                'max_length': 'Længden af `Fornavn må ikke overstige 16 tegn.`'})
Same as above, should be 'Længden af `Fornavn` må ikke overstige 16 tegn.'

2022-11-18 14:54 UTC, Nielswps commented on stregsystem/forms.py
> +                                               'max_length': 'Længden af `Efternavn må ikke overstige 16 tegn.`'})
Same as above, should be 'Længden af `Efternavn` må ikke overstige 16 tegn.'

2022-11-18 14:54 UTC, Nielswps commented on stregsystem/migrations/0016_auto_20220131_2109.py
> +                ('due', models.IntegerField(default=20000)),
Consider adding a comment about what 20000 represents. I assume that it is 200,00 DKK in øre?

2022-11-18 14:54 UTC, Nielswps commented on stregsystem/models.py
> +    due = models.IntegerField(default=200 * 100)
IMO: Either write 20000 as in `stregsystemet/models.py` or do this there as well, to be consistent

2022-11-24 11:50 UTC, jonasKjellerup commented on stregsystem/models.py
> +    due = models.IntegerField(default=200 * 100)
I assume you mean as in `[stregsystem/migrations/0016_auto_20220131_2109.py](https://github.com/f-klubben/stregsystemet/pull/297/files/90af2f04a8eb117a6597404182d6616b5036601b#diff-ff4bbb2f164add9b3111918d75b6a5830763528bfe98589659b83c3c58099373)`. The migrations files are auto generated, hence the discrepancy based on the class from the model file, so it doesn't really make sense to edit them.

2023-09-05 19:34 UTC, krestenlaust commented
Fixes #254

2024-03-27 10:34 UTC, krestenlaust commented on stregsystem/models.py
> +    due = models.IntegerField(default=200 * 100)
Wouldn't it be better to define the membership cost outside of the model to not require migrations in-case of vedtægtsændringer?

2024-03-27 10:34 UTC, krestenlaust commented
I've just looked into this implementation to make sure that #407 doesn't make this outdated, it doesn't look like it. It just needs to catch up with upstream (66 commits behind)

2024-04-26 07:47 UTC, JakobTopholt commented
This pull request would be a godsent.

2024-05-01 20:49 UTC, krestenlaust commented on stregsystem/models.py
> +    due = models.IntegerField(default=200 * 100)
I guess it's just a default

2024-05-18 10:38 UTC, krestenlaust commented
Working towards the following feature:
At a meeting with the forstyrrelse, it was decided that it would be preferable to have a view like MobilePayTool to accept signups manually

2024-06-08 17:07 UTC, krestenlaust reviewed
Initial reviews are welcome🙌

Major changes in this PR:
 - Introduced new model PendingSignup, which only exists to track members who isn't approved and hasn't paid membership due.
 - Turned existing Mobilepaytool abstract, and implemented a signup tool with the same concept.
 - Some refactoring of the AutoPayment-command to properly process paying towards membership dues.

Missing features:
 - [ ] 'Area of Study'-choice in the signup form to populate 'notes' of the member.
 - [ ] ~~'Reject'-functionality for Signup-Tool hasn't been implemented yet.~~ **Feature rejected for now.**
 - [ ] ~~Haven't added QR-code to error_signupdue-screen (Presented when trying to access user menu with member without due paid)~~ **This feature won't be implemented here.**

Known bugs:
 - [x] ~~Approving a member who has already paid their due, will not remove the pending signup-object.~~ **Fixed**
 - [ ] I also suspect there are some issues related to email triggers, depending on the order a user is approved and due is paid.

I'll try to add some more email tests

2024-08-25 10:19 UTC, krestenlaust commented
Feature is finished! I've decided to ignore the potential bug with welcome emails for now.

2024-08-27 11:31 UTC, BoAnd commented
As I see it the sign up logic works. There is some small problem with the differences sign up templates.
Like we could merge template **error_signupdue.html** and **error_signup_not_approved.html** into one template. 

But I think it could be nice to just merge this into prod and the fix the problems afterwards (If there is any :dagger:).

2024-08-27 11:32 UTC, BoAnd approved these changes

2024-08-27 18:02 UTC, merged

2024-08-27 18:31 UTC, krestenlaust commented
> As I see it the sign up logic works. There is some small problem with the differences sign up templates. Like we could merge template **error_signupdue.html** and **error_signup_not_approved.html** into one template.
> 
> But I think it could be nice to just merge this into prod and the fix the problems afterwards (If there is any 🗡️).

Thank you for your review! I've made another issue with your note