Feature tickets
f-klubben/stregsystemet pull request #302
Opened 2022-04-12 15:26 UTC by JohanThomsen

A feature which allows someone to attach an event to product, which will the be shown in the "Mine Billeter" tab found on the userprofile, allowing a user to easily keep track of and remember exact times of events they have bought tickets for.

The page can be found by going to the user profile and clicking "Mine Billeter"
![minebilleter](https://user-images.githubusercontent.com/56736335/162996640-bd9d94eb-78be-4653-adc4-580e9b0f5964.jpg)
In here You can see the tickets the person has bought:
![Billetside](https://user-images.githubusercontent.com/56736335/162996707-e8cb43c5-b374-4ed6-b6da-f62afb82d916.jpg)

The tickets are created by attaching an event to a product, using the following form:
![tomAddEvent](https://user-images.githubusercontent.com/56736335/162996866-f0425e5f-d712-4ec8-b3ee-6eb6ea53fa1d.jpg)
Name = The name of the event (F-acking for example)
Active = Whether the event is active or nor
Time = The start of the even
Ticket start Threshold = The time from which the ticket will be visible on the "mine billeter" page
Ticket end Threshold = The time at which the ticket will no longer be visible on the "mine billeter" page

Here is how it could look when filled out
![FuldAddEvent](https://user-images.githubusercontent.com/56736335/162997327-970e81e2-8535-4754-9c8b-41a4a21dc06f.jpg)

Tests are also added

2022-04-12 16:15 UTC, falkecarlsen requested changes
Looks good! Seems like tests are mostly just yoinked from previous Product tests - that's probably fine.

2022-04-12 16:15 UTC, falkecarlsen commented on stregsystem/views.py
> +    kek = 2
```suggestion
```

2022-04-12 16:15 UTC, falkecarlsen commented on stregsystem/templates/stregsystem/menu_ticketsview.html
> +<h1>{{kek}}</h1>
eksdee 
![image](https://user-images.githubusercontent.com/11318702/163007092-2ac5f588-24d3-43a1-a763-a1a83ce3acb8.png)

2022-04-21 20:26 UTC, hrjakobsen requested changes

2022-05-11 15:00 UTC, falkecarlsen commented
@JohanThomsen will you resolve the comments from @hrjakobsen, then we'll deploy it soon:tm:

2023-10-27 17:08 UTC, merged