Added api endpoints
f-klubben/stregsystemet pull request #320
Opened 2022-10-19 10:50 UTC by Zaph-x

This pull request aims to get us closer to moving away from a monolithic application.
This is done by creating API endpoints, which exposes mostly public facing data in stregsystemet through GET requests.
Furthermore, a sale endpoint which accepts POST requests has been added.

2022-10-19 11:52 UTC, falkecarlsen requested changes
Needs some polish and **definitely** tests but cool :+1:

2022-10-19 11:52 UTC, falkecarlsen commented on stregsystem/views.py
> +    return JsonResponse({'member_id': member.id})
No check for whether DRM returns object, also for all other endpoints

2022-10-19 11:52 UTC, falkecarlsen commented on stregsystem/views.py
> +@csrf_exempt
Would be nice if we *could* retain this

2022-10-19 11:52 UTC, falkecarlsen commented on stregsystem/views.py
> +            room = Room.objects.get(pk=room)
Needs error check if room does not exist

2022-10-25 09:50 UTC, Zaph-x commented on stregsystem/views.py
> +@csrf_exempt
As discussed in person, it would be difficult to retain it at this state. If we were to retain it, we would need to store cookies, which is what this PR tries to avoid. This is because I wish to avoid making as many requests with applications such as STS.

2022-11-11 13:31 UTC, jonasKjellerup requested changes
The handling of error states is in some cases a bit inconsistent (there are quite a few conditions that cause internal server error response).

Otherwise most things seem to work as expected (based on some manual testing)

2022-11-11 13:31 UTC, jonasKjellerup commented on stregsystem/views.py
> +    if request.method == 'POST':
This should return a `HttpResponse` of some sort, since a GET request currently results in a internal server error. Should ideally result in a 405 Method Not Allowed.

2022-11-11 13:31 UTC, jonasKjellerup commented on stregsystem/views.py
> +            return HttpResponseBadRequest("Invalid member_id")
The typing of these parameters is a bit inconsistent. Both `room` and `member_id` are supposed to be numbers, but `member_id` is required to be passed as a string (since `.isdigit()` does not exist for integers - this also causes a internal server error) and `room` is required to be passed as a number.

Ideally it should just parse them if necessary and accept the as if when given integers. But at a minimum it should be consistent.

2022-11-11 13:31 UTC, jonasKjellerup commented on stregsystem/views.py
> +            return HttpResponseBadRequest("Username does not match member_id")
Is there a reason for requiring a user identifier both as a parameter in the post body and as a part of the buystring?

2022-11-15 15:10 UTC, jonasKjellerup approved these changes

2023-05-17 14:21 UTC, merged