added a random function to randomly distribute news entries
f-klubben/stregsystemet pull request #347
Opened 2023-08-25 09:36 UTC by Dev-Destructor

fixes #346

2023-08-25 11:29 UTC, VirtualSatai approved these changes
LGTM :shipit:

2023-08-25 13:09 UTC, falkecarlsen requested changes
Doesn't pass tests as the empty set, as random.choice([]) is an error

2023-08-25 13:09 UTC, falkecarlsen commented on stregsystem/views.py
> +        news_items = News.objects.filter(stop_date__gte=current_time, pub_date__lte=current_time)
```suggestion
        news_items = News.objects.filter(stop_date__gte=current_time, pub_date__lte=current_time).order_by('?').first()
```
https://docs.djangoproject.com/en/dev/ref/models/querysets/#django.db.models.query.QuerySet.order_by

2023-08-25 17:06 UTC, Dev-Destructor commented
> Doesn't pass tests as the empty set, as random.choice([]) is an error

Yeah, Sorry

2023-09-03 09:33 UTC, falkecarlsen approved these changes
Removed unnecessary random.choice call on list of one elem.

Thanks :shipit:

2023-09-03 09:34 UTC, merged