Add none handling in mobilepay-payments
f-klubben/stregsystemet pull request #403
Opened 2023-12-15 11:35 UTC by krestenlaust

2023-12-15 11:39 UTC, falkecarlsen requested changes

2023-12-15 11:39 UTC, falkecarlsen commented on stregsystem/management/commands/importmobilepaypayments.py
> +            self.write_error("read token from storage. 'tokens' is None")
Would be great to have the backup token be copied in on errors and either returning or rerunning the import.

If immediately rerunning there **needs** to be a delay sufficient to not trigger API to rate-limit us and preferably also a backoff. If this is not done, we risk burying the server in IO-operations.

2024-02-21 09:38 UTC, krestenlaust commented on stregsystem/management/commands/importmobilepaypayments.py
> +            self.write_error("read token from storage. 'tokens' is None")
Are you proposing that we load the `tokens.json.bak` instead when `token.json` can't be loaded?

2024-02-21 09:41 UTC, falkecarlsen commented on stregsystem/management/commands/importmobilepaypayments.py
> +            self.write_error("read token from storage. 'tokens' is None")
Yes. We never write to tokens.json.bak except the first time that we populate it from the backup in my home-dir.

2024-02-22 14:27 UTC, krestenlaust commented
I've implemented a crude solution as I understood it now.

P.s. do you know why black keeps failing, even though I can't find any format suggestions locally @falkecarlsen ? I think it might be whitespace related, I tried fixing it in #408

2024-02-23 12:08 UTC, falkecarlsen approved these changes

2024-02-25 17:03 UTC, merged