Improve API (API 1.1)
f-klubben/stregsystemet pull request #421
Opened 2024-04-07 20:42 UTC by krestenlaust

The PR #420 aims to document the API. This PR addresses inconsistensies found during the documentation.

2024-04-08 22:10 UTC, krestenlaust commented
QR-endpoint apparently uses Stregdollars as opposed to Stregøre. I feel like streamlining this is too big a change.
The QR-endpoint also takes a `member` parameter, which will probably be renamed to `username` to streamline with other Member API-methods. (`member` will probably still be supported)

2024-04-17 06:55 UTC, krestenlaust commented
![](https://github.com/f-klubben/stregsystemet/assets/17174333/13cb5b85-4a4e-450b-927a-87d2fd1231f1)
Changed response text on error to this format

2024-05-04 22:13 UTC, krestenlaust commented
Changed format for Category_mapping endpoint output:
`{"1": [], "2": [], "3": [], "13": [], "32": [[6, "kaffe"]], "33": [], "34": []}` -> `{"1": [], "2": [], "3": [], "13": [], "32": [{"category_id": 6, "category_name": "kaffe"}], "33": [], "34": []}`

Much more verbose, but it's more like the other endpoints. Considering changing it to not return products which don't have any mapped categories

2024-10-24 13:48 UTC, krestenlaust commented
I've decided to leave the sales API as is

2024-11-13 20:56 UTC, Mast3rwaf1z requested changes
a few small changes, but looks nice :+1:

2024-11-13 20:56 UTC, Mast3rwaf1z commented on stregsystem/urls.py
> +    re_path(r'^api/products/named_products$', views.dump_named_products, name="dump_named_products"),
why not `get_named_products` and `get_active_products`? this change seems related to making better function names, so why not follow what is above?

2024-11-13 20:56 UTC, Mast3rwaf1z commented on stregsystem/views.py
> -    data = 'mobilepay://send?{}'.format(urllib.parse.urlencode(query))
remove urllib.parse import

2024-11-13 20:56 UTC, Mast3rwaf1z commented on stregsystem/views.py
> +        return HttpResponseBadRequest("Member not found")
The rest of these error messages are prefixed with something like `Parameter missing:` but not this one

Edit: i see more that aren't prefixed as well, i think it would be nice to have them all prefixed like that

2024-11-13 20:56 UTC, Mast3rwaf1z commented on stregsystem/forms.py
> +    amount = forms.DecimalField(min_value=0.01, decimal_places=2, required=False)
I don't see the point in this change? don't we disallow payments below 50?

2024-11-15 12:14 UTC, Mast3rwaf1z commented on stregsystem/forms.py
> +    amount = forms.DecimalField(min_value=0.01, decimal_places=2, required=False)
also when i send a request to `http://localhost:8000/api/member/payment/qr?member=tester&amount=0.01` it fails, while `amount=0.02` doesn't

2024-11-27 23:43 UTC, krestenlaust commented on stregsystem/views.py
> +        return HttpResponseBadRequest("Member not found")
This should be fixed by 40e878f

2024-11-27 23:43 UTC, krestenlaust commented on stregsystem/forms.py
> +    amount = forms.DecimalField(min_value=0.01, decimal_places=2, required=False)
Changed in cdaff44

2024-11-28 14:20 UTC, krestenlaust commented on stregsystem/views.py
> -    data = 'mobilepay://send?{}'.format(urllib.parse.urlencode(query))
Fixed by dba5abd

2024-11-28 14:33 UTC, krestenlaust commented on stregsystem/urls.py
> +    re_path(r'^api/products/named_products$', views.dump_named_products, name="dump_named_products"),
I've updated the methods by 3c9f739
I've tried changing the naming convention further by f0f5b50

2024-11-29 21:41 UTC, merged