Feature: Mail/download userdata
f-klubben/stregsystemet pull request #434
Opened 2024-04-25 20:57 UTC by Mast3rwaf1z

The idea is to allow users to download all their user data, either locally or over email

To avoid people downloading to strandvejen i should probably also add some way to hide the download button there, or omit it all together...

2024-04-26 11:33 UTC, Mast3rwaf1z commented
@krestenlaust i think this is a working version, but i have no way of testing whether the mails are being sent properly, do you have an idea?

2024-04-26 11:50 UTC, krestenlaust commented
I think I'll try to do a review just now, and then we can find a way to test it afterwards. But haven't you been able to set up a local mailserver before?

2024-04-26 11:58 UTC, Mast3rwaf1z commented
i'll see if i can find something to test with, but the main problem is whether i'd be spamming anything, so i figured i'd ask if you used something to test mails from stregsystemet

2024-04-26 12:01 UTC, Mast3rwaf1z commented
https://github.com/mailhog/MailHog seems good enough, i'll test it some more before putting it ready for review

2024-04-26 12:03 UTC, krestenlaust requested changes
Nice work! I've added some comments, if there's anything you'd like expanded or so, we can just find a day to look at it at the same time :D

2024-04-26 12:03 UTC, krestenlaust commented on stregsystem/templates/stregsystem/sent_csv_mail.html
> +{% endblock %}
I'd imagined that the functionality could be incoperated into the existing "User-info" page, maybe in the bottom of user-info, (Instead of adding a whole other page)

2024-04-26 12:03 UTC, krestenlaust commented on stregsystem/urls.py
> +    re_path(r'^(?P<room_id>\d+)/send_csv_mail/(?P<member_id>\d+)/$', views.send_csv_mail, name="send_csv_mail"),
If this endpoint is still needed, I think it should be moved above the API call section of urls

2024-04-26 12:03 UTC, krestenlaust commented on stregsystem/templates/stregsystem/sent_csv_mail.html
> +    <h2>Ærede fember ({{member.username}}), hvis du ikke har efterspurgt data de sidste 10 dage, skulle du gerne have modtaget en email.</h2>
I was thinking more in the lines of 10 minutes rather than 10 days

2024-04-26 12:06 UTC, krestenlaust commented
> https://github.com/mailhog/MailHog seems good enough, i'll test it some more before putting it ready for review

No worries, I'll make sure to review again when you're ready 👌

2024-04-26 12:06 UTC, Mast3rwaf1z commented on stregsystem/mail.py
> +    return True
i was thinking the same, but it is a draft pr after all :)

2024-04-26 12:07 UTC, Mast3rwaf1z commented on stregsystem/templates/stregsystem/sent_csv_mail.html
> +{% endblock %}
the problem was that i didn't want to load the entire tables every time a user would access the page

2024-04-26 12:29 UTC, Mast3rwaf1z commented
it works using `mailhog -smtp-bind-addr 0.0.0.0:25`, but i'd like to have a new column in the member table called like `last_data_request` but adding it to the member object in models.py doesn't work, how do i go about adding a column?

2024-04-27 08:01 UTC, krestenlaust commented on stregsystem/mail.py
> +    return True
No worries!

2024-04-27 08:24 UTC, krestenlaust commented on stregsystem/templates/stregsystem/sent_csv_mail.html
> +{% endblock %}
Hmm I get that argument, it would probably be easiest to simply have it that way. Otherwise you should do like with purchases (the same page is returned with purchase info) and return to the same page with arguments

2024-04-28 16:19 UTC, krestenlaust requested changes
Overall great improvement and awesome work

Is it possible for you to rename references from CSV to something like userdata. "send_csv.html" to "send_userdata.html", "sent_userdata_mail.html" etc. As CSV is an implementation detail.

If all these requests are too much work, then please let me know, and I'll give a hand, as this is an awesome idea.

2024-04-28 16:19 UTC, krestenlaust commented on stregsystem/mail.py
> +def send_template_mail(member, target_template: str, context: dict, subject: str, attachments: dict = {}):
Nice work updating the send template mail 👌

2024-04-28 16:19 UTC, krestenlaust commented on stregsystem/models.py
> +    requested_data_time = models.DateTimeField(blank=True, null=True, default=timezone.datetime.fromtimestamp(0))
I don't think this change is worth updating the member model, though nice work anyhow with your implementation draft. I think it's fine to just have it in an transient dictionary like you did previously. Or something like that. I'm not entirely sure, maybe we should just discuss this face-to-face some time

2024-04-28 16:19 UTC, krestenlaust commented on stregsystem/mail.py
> +    payments_csv += "\n".join([f'{payment.timestamp},{payment.amount}' for payment in payments])
It could be cool to also tell which payments are MobilePay automated, even though it's an implementation detail on our part.

There's a model called MobilePayment you can look into for this, I'm not entirely sure how it works

2024-04-28 16:19 UTC, krestenlaust commented on stregsystem/templates/mail/send_csv.html
> +        Hermed har du din bruger data i stregsystemet i form af csv filer.
```suggestion
        Ærede fember - {{fember}}

        Du har anmodet om at få tilsendt al den brugerdata vi har opbevaret af din bruger. Din data er vedhæftet som CSV-filer.
        
        *Indsæt hilsen fra de andre mails*
        ---
        *Write in english*
```

2024-04-28 16:19 UTC, krestenlaust commented on stregsystem/views.py
> +    mail_sent_text = "Mail sendt!" if _send_csv_mail(member) else "Ingen mail sendt."
Maybe pass a boolean instead, and have this condition in the template instead.

2024-04-28 19:08 UTC, Mast3rwaf1z commented on stregsystem/mail.py
> +    userdata_csv += f"{member.id},{member.username},{member.firstname},{member.lastname},{member.email},{member.year}"
I disagree, why should we generate additional IO by using this library to write a file? This library looks to be for creating files, atm i'm just making a bytestream from memory, while if i used this library i would have to make a csv writer object, write the database into a file with this object, read the file, convert it to a csv reader, convert that to a string and then i can attach it

seems like a ton of unnecessary IO, but i might be wrong, its just a quick google search

as for spaces, yes that was a mistake :P

2024-04-28 19:09 UTC, Mast3rwaf1z commented on stregsystem/models.py
> +    requested_data_time = models.DateTimeField(blank=True, null=True, default=timezone.datetime.fromtimestamp(0))
what was there before with the dict didn't work, the state was not saved between loads of the page, hence i wanted to store it in the database

2024-04-28 20:40 UTC, Mast3rwaf1z commented on stregsystem/mail.py
> +    payments_csv += "\n".join([f'{payment.timestamp},{payment.amount}' for payment in payments])
it should work now, although i don't know how to test it, as it seems the db has no payment objects in any of the testdata?

2024-04-28 20:49 UTC, Mast3rwaf1z commented on stregsystem/templates/stregsystem/sent_csv_mail.html
> +{% endblock %}
i'll close this one as it sounds like its good

2024-04-28 20:52 UTC, Mast3rwaf1z commented on stregsystem/mail.py
> +        if member.requested_data_time > ten_minutes_ago:
so you're thinking adding it to a config file? makes sense

2024-04-29 09:14 UTC, krestenlaust requested changes
These are the final changes I can think of. Should be ready to go after this!

2024-04-29 09:14 UTC, krestenlaust commented on stregsystem/templates/stregsystem/sent_userdata.html
> +    <h2>Ærede fember ({{member.username}}), hvis du ikke har efterspurgt data de sidste 5 minutter, skulle du gerne have modtaget en email.</h2>
You already know whether a mail was sent (`mail_sent`), so I think this text should just adapt to that. I get the joking tone, but I think the 'honored fember' part is a bit too modest. Maybe just start the text with "Du skulle gerne have modtaget en mail..." somthing along those lines depending on whether the mail was sent or not

2024-04-29 09:14 UTC, krestenlaust commented on stregsystem/templates/stregsystem/sent_userdata.html
> +    Sidst du fik sendt mail: <b>{{sent_time}}</b><br>
Since this isn't stored in the model anymore, we can't really expect it to know the time. So we should probably only serve this time, if the mail isn't sent, "Du fik tilsendt en mail 2 minutter siden, vent til 5 minutter" or something along those lines.

2024-04-29 09:14 UTC, krestenlaust commented on stregsystem/urls.py
> +    re_path(r'^(?P<room_id>\d+)/send_csv_mail/(?P<member_id>\d+)/$', views.send_userdata, name="send_csv_mail"),
This still needs to be moved

2024-04-29 11:26 UTC, Mast3rwaf1z commented
just quickly went over your review in my lunch break :)

could you please take a look at the two comments i haven't closed further up? @krestenlaust

2024-04-29 13:57 UTC, krestenlaust approved these changes
Nice work! LGTM

@falkecarlsen this issue is related to GDPR and serving userdata. Have you got an opinion regarding the implementation or otherwise ?

2024-05-02 08:04 UTC, BoAnd commented
LGTM

2024-05-02 08:07 UTC, BoAnd approved these changes

2024-05-02 09:41 UTC, krestenlaust commented
@Mast3rwaf1z you may merge whenever :D If you at some point in the future feel like doing more on this feature, then adding more tests would be cool

2024-05-02 15:07 UTC, merged