[Feature] Nix Flake
f-klubben/stregsystemet pull request #459
Opened 2024-05-18 17:43 UTC by Mast3rwaf1z

Added a nix flake, i have 3 things i'd like to test out with this, what is in this PR atm is just some things from #272 and some things from f-klubben/fnix#2

What i would like this flake to also do is to run the system by just calling `nix run github:f-klubben/stregsystemet` kinda like how its handled in https://github.com/f-klubben/stregsystemet-cli/blob/master/default.nix

2024-06-07 21:19 UTC, Mast3rwaf1z commented
Still not done at all, the default package does not want to link the python packages properly, and as such the python path only works while working with the devshell

but to be fair, you wouldn't use a flake-based default package in a server side program without the devshell if its available? hmm

2024-09-09 18:49 UTC, AshesOfEther approved these changes

2024-09-24 21:52 UTC, krestenlaust requested changes

2024-09-24 21:52 UTC, krestenlaust commented on requirements.txt
Is it neccesary to add these comments to the requirements? I think it might confuse/intimidate people only interesting in the python aspect of the project

2024-09-25 14:23 UTC, Mast3rwaf1z commented
it *should* work still, without the comments :)

2024-11-29 18:32 UTC, krestenlaust approved these changes
Sorry for slow review! I'd mistaken it as unfinished.

LGTM! :shipit: 

You can merge at will!

2024-11-29 18:48 UTC, Mast3rwaf1z commented
> You can merge at will!

sure, let me just update the fork and test if it still works

2024-11-29 19:17 UTC, Mast3rwaf1z commented
i've updated the flake lock as well, so the newest nixpkgs can be used, everything still works so i'll merge

2024-11-29 19:18 UTC, merged