Duplicate query removal when buying
f-klubben/stregsystemet pull request #469
Opened 2024-06-12 17:45 UTC by patrickreiffenstein

Partially fixes issue #357.

2024-06-13 07:50 UTC, krestenlaust reviewed
I'll have to run it locally to check things over, and verify that we have tests in place

2024-06-13 07:50 UTC, krestenlaust commented on stregsystem/models.py
> +        Sales = []
```suggestion
        sales = []
```

2024-06-13 07:50 UTC, krestenlaust commented on stregsystem/models.py
> +                Sales.append(s)
```suggestion
                sales.append(s)
```

2024-08-05 11:21 UTC, krestenlaust commented
I'll try to review this before summer ends

2024-09-09 12:43 UTC, JakobTopholt commented
@Mast3rwaf1z Vil du ikke være en king og review den her så Kresten kan få lidt fritid?

2024-09-09 14:31 UTC, krestenlaust commented
♥️ jeg vil dog stadig gerne merge den

2024-09-09 14:36 UTC, Mast3rwaf1z commented
> @Mast3rwaf1z Vil du ikke være en king og review den her så Kresten kan få lidt fritid?

Tager lige et kig senere, var lige til forelæsning

2024-09-09 16:33 UTC, Mast3rwaf1z requested changes
Some small things, i think improves readability of the code, and removed some redundant constructor calls?

also i believe by using `_` in a for loop prevents memory being allocated to the variable. really insignificant but hey, its good to have imo

2024-09-09 16:33 UTC, Mast3rwaf1z commented on stregsystem/models.py
> +        Sale.objects.bulk_create(Sales)
```suggestion
        Sale.objects.bulk_create(sales)
```

2024-09-09 16:33 UTC, Mast3rwaf1z commented on stregsystem/views.py
> +                unique_product_dict[str(unique_id)] += 1
```suggestion
            if unique_id not in unique_product_dict:
                unique_product_dict[unique_id] = 1
            else:
                unique_product_dict[unique_id] += 1
```
what's the point in converting from an int object to string all the time?

2024-09-09 16:33 UTC, Mast3rwaf1z commented on stregsystem/views.py
>                  Q(rooms__id=room.id) | Q(rooms=None),
```suggestion
        for key, value in unique_product_dict.items():
            product = Product.objects.get(
                Q(pk=key),
                Q(active=True),
                Q(deactivate_date__gte=time_now) | Q(deactivate_date__isnull=True),
                Q(rooms__id=room.id) | Q(rooms=None),
```

2024-09-09 16:33 UTC, Mast3rwaf1z commented on stregsystem/views.py
> +            products.extend([product for x in range(unique_product_dict[str(i)])])
```suggestion
            products.extend([product for _ in range(value)])
```

2024-09-09 16:44 UTC, Mast3rwaf1z commented on stregsystem/views.py
> +                unique_product_dict[str(unique_id)] += 1
you can also optimize it further by just using dict comprehension:

```py
unique_product_dict = {i:bought_ids.count(i) for i in bought_ids}
```

2025-01-13 17:16 UTC, Mast3rwaf1z approved these changes
looks good, minor annoying naming issue

2025-01-13 17:16 UTC, Mast3rwaf1z commented on stregsystem/views.py
> +
inconsistent naming, sale and purchase

2025-01-13 17:34 UTC, Mast3rwaf1z commented on stregsystem/views.py
>          return "Invalid product id", 400, i
```suggestion
        return "Invalid product id", 400, key
```

2025-01-13 17:43 UTC, patrickreiffenstein commented on stregsystem/views.py
>          return "Invalid product id", 400, i
Should be fixed now

2025-01-13 17:45 UTC, patrickreiffenstein commented on stregsystem/views.py
> +
Fixed

2025-10-08 10:44 UTC, patrickreiffenstein commented
My fork is broken and I don't know why it acts that way, so these changes are moved to #589.

2025-10-08 10:44 UTC, closed without merging