stregreport: Add all categories to overview
f-klubben/stregsystemet pull request #532
Opened 2024-11-30 00:00 UTC by krestenlaust

The current implementation is very crude and hardcodes the product IDs.
Instead we should use the categories, and make it dynamic.

Fixes #514

2024-11-30 00:10 UTC, krestenlaust commented
The fixture doesn't have any transactions, so it can't easily be tested (Without me having to go through great amounts of pain)
![Screenshot of the new screen, where a bunch of categories are grouped tightly together](https://github.com/user-attachments/assets/46404158-7cb0-4250-8f56-996363b74021)

You could argue that the styling should be updated. But then I might argue that this admin page is already still 10x more useful now, than it ever has been (Of course, I don't mind, not having to mess around with styling)

2024-12-01 12:51 UTC, Mast3rwaf1z requested changes
there's a few small questions, descide for yourself whether you want to fix any of them, but i don't think there's anything wrong with the current code

good change :+1:

2024-12-01 12:51 UTC, Mast3rwaf1z commented on stregreport/views.py
>          return render(request, 'admin/stregsystem/report/error_ranksnotfound.html', locals())
when you're redesigning stregreport anyway, isn't this kind of a useless check?

2024-12-01 12:51 UTC, Mast3rwaf1z commented on stregreport/views.py
>      to_time = fjule_party(year)
fjule_party, while being a funny name for a function, says very little about what the function does

2024-12-01 12:51 UTC, Mast3rwaf1z commented on stregreport/views.py
> +        stat_lists.append((cat.name, sale_product_rank(get_product_ids_from_category(cat), from_time, to_time)))
i would've probably done something like: 
```py
stat_lists = [(
    cat.name,
    sale_product_rank(get_product_ids_from_category(cat)),
    from_time,
    to_time
) for cat in Category.objects.all()]
```
i think its more readable

2024-12-01 12:51 UTC, Mast3rwaf1z commented on stregreport/views.py
> -    vitamin = [1850, 1851, 1852, 1863, 1880]
wtf

2024-12-01 13:01 UTC, krestenlaust commented on stregreport/views.py
> -    vitamin = [1850, 1851, 1852, 1863, 1880]
It's definitely the most cursed part of the stregsystem, now replaced. I'm also working on the new razzia, hoping to completely remove razzia from `stregreport`-module

2024-12-09 18:03 UTC, krestenlaust commented on stregreport/views.py
>      to_time = fjule_party(year)
Haven't touched the function. But might try to find a better name while I'm at it though

2024-12-09 18:10 UTC, krestenlaust commented on stregreport/views.py
> +        stat_lists.append((cat.name, sale_product_rank(get_product_ids_from_category(cat), from_time, to_time)))
Solved by aac3ee0

2024-12-09 18:32 UTC, krestenlaust commented on stregreport/views.py
>          return render(request, 'admin/stregsystem/report/error_ranksnotfound.html', locals())
Resolved by 9f484d2

2024-12-09 18:40 UTC, krestenlaust commented on stregreport/views.py
>      to_time = fjule_party(year)
The function is widely, I decided that adding type hints, and a real docstring is sufficient for the function to explain itself. A longer name would make adjacent code (adjacent to calls) more noisy to look at

If you disagree you are of course free to suggest further changes👌👌

Resolved by e3edd50

2024-12-09 18:47 UTC, krestenlaust commented
I've tried giving the report types new names to be more explanatory (I've also reordered them)

![billede](https://github.com/user-attachments/assets/ca83c1be-e16c-49fe-a629-5f279ac10c47)

![billede](https://github.com/user-attachments/assets/acff8376-00cf-496d-b954-43db861669c6)

2024-12-09 19:25 UTC, patrickreiffenstein commented on stregreport/views.py
>      from_time = fjule_party(year - 1)
Why is last year variable not used when it is defined right above?

2024-12-09 19:32 UTC, patrickreiffenstein commented on stregreport/views.py
>      from_time = fjule_party(year - 1)
and why is next_year never used :thinking:

2024-12-09 20:06 UTC, patrickreiffenstein commented on stregreport/views.py
>      from_time = fjule_party(year - 1)
This is the only weird stuff I could find and it is really minor. Is it anything you want to change @krestenlaust ? Otherwise I see nothing wrong with this being approved.

2024-12-09 21:47 UTC, krestenlaust commented on stregreport/views.py
>      from_time = fjule_party(year - 1)
It took me a while to remember, but it's actually because they are used in the template, all local variables are 'injected' into the template:
`return render(request, 'admin/stregsystem/report/ranks.html', locals())` <-- locals()

`next_year` was added in #443 to be used in the template. I've decided to move the variables to the bottom to more clearly show that they are used in the template. I decided `year - 1` is still better than using the variable.

Resolved by 5d85f44

2024-12-10 12:21 UTC, patrickreiffenstein approved these changes
Looks good to me

2025-01-13 17:30 UTC, Mast3rwaf1z commented
@krestenlaust  i've just tried running it before my last review and code now, it seems the categories doesn't show properly for me using the testdata?
before:
![Screenshot_20250113_182847](https://github.com/user-attachments/assets/b8d93fa2-20de-4edb-ab5e-001aa27ce1be)
after:
![Screenshot_20250113_182703](https://github.com/user-attachments/assets/b8055b0f-e110-4181-bb06-6c744f497326)

same testdata: testdata.json

2025-01-14 13:45 UTC, krestenlaust commented
> @krestenlaust i've just tried running it before my last review and code now, it seems the categories doesn't show properly for me using the testdata?

After bisecting, it turns out it was the 'pythonic' implementation that was faulty. I ended up simply reverting it, because it (to me) is actually harder to understand than the current imperative. Let me know what you think

2025-01-15 07:14 UTC, Mast3rwaf1z approved these changes
lgtm, works on my machine :+1:

2025-01-15 09:28 UTC, merged