Get rid of tabindex
f-klubben/stregsystemet pull request #540
Opened 2024-12-10 18:38 UTC by atjn

Tabindexes change the expected flow of the page to make it less intuitive, we should get rid of them.

2024-12-10 21:19 UTC, krestenlaust requested changes
I partly disagree. Every other page than the frontpage should have tabindexes removed.

But I think the frontpage should be in this order: Quickbuy -> buy -> restart -> menu -> tilmeld. I feel like it's more intuitive for them to be in that order🤔 Even though it isn't standard web. My main argument for us to ignore the web in this sense, is the way it's accessed (through the stregkiosk) it doesn't feel like a webpage, it's closer to a kind of game.

2024-12-10 21:40 UTC, atjn commented
> I feel like it's more intuitive for them to be in that order🤔

The first time I used the stregsystem, I wanted to access the menu, so I pressed `Shift` + `Tab` because that moves you back up towards the header in almost all apps, but the stregsystem did something else which confused me, so now I just always use the mouse.

2025-01-11 20:15 UTC, krestenlaust commented
Should we maybe make a kind of design guideline? To point to, with discussions like these 🤔

2025-01-12 01:02 UTC, atjn commented
Sounds good to me.

2026-06-17 00:53 UTC, krestenlaust approved these changes
LGTM

We'll see how long this lasts (till someone makes a pr for the opposite again xd)

2026-06-17 00:55 UTC, merged